name: artlistener_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1
  audioplayers: ^6.5.1
  wifi_scan: ^0.4.1+2
  cloud_firestore: ^6.0.2
  flutter_tts: ^4.2.3
  firebase_storage: ^13.0.2
  image_picker: ^1.2.0
  sensors_plus: ^5.0.1
  vector_math: ^2.1.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
